application: drillbitsxxx
version: 1
runtime: go
api_version: go1

handlers:

- url: /half-birthday/static
  static_dir: half-birthday/static

- url: /half-birthday
  static_files: half-birthday/index.html
  upload: half-birthday

- url: /.*
  script: _go_app
